use std::path::Path;

use crate::error::Result;

struct EmbeddedFile {
    path: &'static str,
    content: &'static str,
}

// Generated by build.rs: scans skills/ and pipelines/ at compile time.
include!(concat!(env!("OUT_DIR"), "/builtin_files.rs"));

/// Write all built-in skills and pipeline templates into the project directory.
/// Skips files that already exist to avoid overwriting customizations.
pub fn install_builtins(project_root: &Path) -> Result<Vec<String>> {
    let mut installed = Vec::new();

    for file in BUILTIN_FILES {
        let dest = project_root.join(file.path);
        if dest.exists() {
            continue;
        }
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&dest, file.content)?;
        installed.push(file.path.to_string());
    }

    Ok(installed)
}
