use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::scanner::DiscoveredDoc;

/// A bootstrap plan generated by an LLM based on project analysis.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BootstrapPlan {
    /// Namespaces (product domains) discovered in the project
    pub namespaces: Vec<BootstrapNamespace>,
    /// Brief summary of analysis
    #[serde(default)]
    pub summary: String,
}

/// A namespace (product domain) in a bootstrap plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BootstrapNamespace {
    /// Namespace name (e.g. "backend-api", "mobile-app")
    pub name: String,
    /// Description of this product domain
    #[serde(default)]
    pub description: String,
    /// Specs under this namespace
    pub specs: Vec<BootstrapSpec>,
}

/// A spec within a namespace in a bootstrap plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BootstrapSpec {
    /// Spec name (e.g. "jwt-migration", "auth-system")
    pub name: String,
    /// Description of this spec
    #[serde(default)]
    pub description: String,
    /// Tags for matching issues to this spec
    #[serde(default)]
    pub tags: Vec<String>,
    /// Existing documents to import as references
    #[serde(default)]
    pub documents: Vec<BootstrapDoc>,
}

/// A document to import as part of bootstrap.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BootstrapDoc {
    /// Relative file path in the project
    pub path: String,
    /// Document type (e.g. "reference", "imported", "overview")
    pub doc_type: String,
    /// Document title
    #[serde(default)]
    pub title: String,
}

/// Result of executing a bootstrap plan.
#[derive(Debug, Clone, Serialize)]
pub struct BootstrapResult {
    pub namespaces_created: usize,
    pub specs_created: usize,
    pub documents_imported: usize,
    pub summary: String,
    /// Details per namespace/spec for display
    pub details: Vec<BootstrapNamespaceResult>,
}

/// Result details for a single namespace.
#[derive(Debug, Clone, Serialize)]
pub struct BootstrapNamespaceResult {
    pub namespace_name: String,
    pub namespace_id: String,
    pub specs: Vec<BootstrapSpecResult>,
}

/// Result details for a single spec within a namespace.
#[derive(Debug, Clone, Serialize)]
pub struct BootstrapSpecResult {
    pub spec_name: String,
    pub spec_id: String,
    pub documents_imported: usize,
}

/// Build the bootstrap prompt that an LLM uses to generate a BootstrapPlan.
///
/// The prompt includes:
/// 1. Project technical profile (from project-context.md)
/// 2. Project file tree
/// 3. Discovered documentation with content previews
/// 4. Module's bootstrap.md instructions
/// 5. Expected JSON response schema
pub fn build_bootstrap_prompt(
    project_context: &str,
    file_tree: &str,
    discovered_docs: &[DiscoveredDoc],
    bootstrap_md: Option<&str>,
) -> String {
    let mut prompt = String::new();

    prompt.push_str("You are analyzing a software project to understand its structure and propose how to organize its documentation.\n\n");

    prompt.push_str("## Project Technical Profile\n\n");
    prompt.push_str(project_context);
    prompt.push_str("\n\n");

    prompt.push_str("## Project File Tree\n\n");
    prompt.push_str(file_tree);
    prompt.push_str("\n\n");

    prompt.push_str("## Discovered Documentation\n\n");
    if discovered_docs.is_empty() {
        prompt.push_str("No documentation files found.\n");
    } else {
        for doc in discovered_docs {
            prompt.push_str(&format!("### {} ({} bytes)\n\n", doc.path, doc.size));
            if !doc.preview.is_empty() {
                prompt.push_str("```\n");
                prompt.push_str(&doc.preview);
                prompt.push_str("\n```\n");
            }
            prompt.push('\n');
        }
    }
    prompt.push('\n');

    prompt.push_str("## Module Bootstrap Instructions\n\n");
    match bootstrap_md {
        Some(content) => prompt.push_str(content),
        None => prompt.push_str("No specific bootstrap instructions provided."),
    }
    prompt.push_str("\n\n");

    prompt.push_str("## Your Task\n\n");
    prompt.push_str(
        "Analyze this project and produce a bootstrap plan as JSON.\n\n\
         Your job is ONLY to organize the project into namespaces and specs:\n\
         - **Namespaces** represent product domains (e.g. \"backend-api\", \"mobile-app\", \"shared-infra\")\n\
         - **Specs** represent specification document collections for a specific concern (e.g. \"auth-system\", \"payment-integration\")\n\
         - **Tags** on specs help match future issues to the right spec\n\n\
         Do NOT choose pipelines or skills — those are selected later when an issue is started.\n\n\
         Import any existing documentation as reference documents under the appropriate spec.\n\n\
         IMPORTANT: Propose clear, descriptive names for namespaces and specs.\n\
         The user will review and may rename them before applying.\n\n\
         Respond with ONLY valid JSON in this format:\n\
         ```json\n\
         {\n  \
           \"namespaces\": [\n    \
             {\n      \
               \"name\": \"backend-api\",\n      \
               \"description\": \"Backend REST API service\",\n      \
               \"specs\": [\n        \
                 {\n          \
                   \"name\": \"auth-system\",\n          \
                   \"description\": \"Authentication and authorization\",\n          \
                   \"tags\": [\"auth\", \"login\", \"jwt\", \"session\"],\n          \
                   \"documents\": [\n            \
                     {\"path\": \"docs/auth.md\", \"doc_type\": \"reference\", \"title\": \"Auth Design Notes\"}\n          \
                   ]\n        \
                 }\n      \
               ]\n    \
             }\n  \
           ],\n  \
           \"summary\": \"Brief description of what you found and why you chose these namespaces\"\n\
         }\n\
         ```\n",
    );

    prompt
}

/// Execute a bootstrap plan: create namespaces, specs, and import reference documents.
///
/// Bootstrap does NOT create pipeline runs or map skills — those happen at `issue start`.
///
/// Returns a summary of actions taken.
pub fn execute_bootstrap_plan(
    plan: &BootstrapPlan,
    project_dir: &Path,
) -> crate::error::Result<BootstrapResult> {
    use crate::helpers::slugify;
    use crate::model::{Document, Namespace, Spec};
    use crate::storage::{FileStorage, IndexDb, ProjectLayout};

    let layout = ProjectLayout::new(project_dir);
    layout.ensure_initialized()?;
    let db = IndexDb::open(&layout.db_path())?;

    let mut total_ns = 0usize;
    let mut total_specs = 0usize;
    let mut total_docs = 0usize;
    let mut details = Vec::new();

    for ns_plan in &plan.namespaces {
        let namespace = Namespace::new(&ns_plan.name, &ns_plan.description);
        db.create_namespace(&namespace)?;
        total_ns += 1;

        let mut spec_results = Vec::new();

        for spec_plan in &ns_plan.specs {
            let spec = Spec::new(&spec_plan.name, &spec_plan.description, &namespace.id);
            db.create_spec(&spec)?;
            total_specs += 1;

            // Import existing documents as references (no pipeline run, no skill)
            let mut imported = 0usize;
            for doc_spec in &spec_plan.documents {
                let source_path = project_dir.join(&doc_spec.path);
                let content = match std::fs::read_to_string(&source_path) {
                    Ok(c) => c,
                    Err(_) => continue,
                };

                let title = if doc_spec.title.is_empty() {
                    doc_spec.path.clone()
                } else {
                    doc_spec.title.clone()
                };

                let mut document = Document::new(
                    &doc_spec.doc_type,
                    &title,
                    "", // no skill — assigned at issue start
                    "", // no pipeline run — created at issue start
                    &spec.id,
                );
                document.status = "final".to_string();
                document.body = content;

                let slug = slugify(&title);
                let dest = layout
                    .artifacts_dir()
                    .join(format!("{}.{}.md", slug, doc_spec.doc_type));
                document.file_path = dest.clone();

                FileStorage::write_document(&document, &dest)?;
                db.upsert_document(&document)?;
                imported += 1;
            }
            total_docs += imported;

            spec_results.push(BootstrapSpecResult {
                spec_name: spec_plan.name.clone(),
                spec_id: spec.id,
                documents_imported: imported,
            });
        }

        details.push(BootstrapNamespaceResult {
            namespace_name: ns_plan.name.clone(),
            namespace_id: namespace.id,
            specs: spec_results,
        });
    }

    Ok(BootstrapResult {
        namespaces_created: total_ns,
        specs_created: total_specs,
        documents_imported: total_docs,
        summary: plan.summary.clone(),
        details,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_build_bootstrap_prompt_basic() {
        let prompt = build_bootstrap_prompt("Rust project", "src/\n  main.rs", &[], None);
        assert!(prompt.contains("## Project Technical Profile"));
        assert!(prompt.contains("Rust project"));
        assert!(prompt.contains("## Project File Tree"));
        assert!(prompt.contains("No documentation files found."));
        assert!(prompt.contains("No specific bootstrap instructions provided."));
        assert!(prompt.contains("## Your Task"));
        assert!(prompt.contains("\"namespaces\""));
        assert!(prompt.contains("\"specs\""));
        assert!(prompt.contains("**Namespaces** represent product domains"));
        // Should NOT mention pipelines or skills
        assert!(!prompt.contains("## Available Skills"));
        assert!(!prompt.contains("## Available Pipelines"));
    }

    #[test]
    fn test_build_bootstrap_prompt_with_docs_and_bootstrap_md() {
        let docs = vec![DiscoveredDoc {
            path: "README.md".into(),
            size: 512,
            preview: "# My Project\nA cool project.".into(),
        }];
        let prompt = build_bootstrap_prompt(
            "Node project",
            "package.json\nsrc/",
            &docs,
            Some("Import README as reference."),
        );
        assert!(prompt.contains("README.md (512 bytes)"));
        assert!(prompt.contains("# My Project"));
        assert!(prompt.contains("Import README as reference."));
        assert!(prompt.contains("\"namespaces\""));
        assert!(prompt.contains("\"tags\""));
    }

    #[test]
    fn test_bootstrap_plan_deserialize() {
        let json = r#"{
            "namespaces": [
                {
                    "name": "backend-api",
                    "description": "Backend API service",
                    "specs": [
                        {
                            "name": "auth-system",
                            "description": "Authentication and authorization",
                            "tags": ["auth", "login", "jwt"],
                            "documents": [
                                {"path": "README.md", "doc_type": "reference", "title": "Project Overview"}
                            ]
                        }
                    ]
                }
            ],
            "summary": "Standard Rust project"
        }"#;
        let plan: BootstrapPlan = serde_json::from_str(json).unwrap();
        assert_eq!(plan.namespaces.len(), 1);
        assert_eq!(plan.namespaces[0].name, "backend-api");
        assert_eq!(plan.namespaces[0].description, "Backend API service");
        assert_eq!(plan.namespaces[0].specs.len(), 1);
        assert_eq!(plan.namespaces[0].specs[0].name, "auth-system");
        assert_eq!(
            plan.namespaces[0].specs[0].tags,
            vec!["auth", "login", "jwt"]
        );
        assert_eq!(plan.namespaces[0].specs[0].documents.len(), 1);
        assert_eq!(
            plan.namespaces[0].specs[0].documents[0].doc_type,
            "reference"
        );
    }

    #[test]
    fn test_bootstrap_plan_deserialize_minimal() {
        let json = r#"{"namespaces": [{"name": "test", "specs": [{"name": "main"}]}]}"#;
        let plan: BootstrapPlan = serde_json::from_str(json).unwrap();
        assert_eq!(plan.namespaces.len(), 1);
        assert_eq!(plan.namespaces[0].name, "test");
        assert_eq!(plan.namespaces[0].description, "");
        assert_eq!(plan.namespaces[0].specs[0].name, "main");
        assert!(plan.namespaces[0].specs[0].tags.is_empty());
        assert!(plan.namespaces[0].specs[0].documents.is_empty());
        assert!(plan.summary.is_empty());
    }
}
