use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::scanner::DiscoveredDoc;

/// A bootstrap plan generated by an LLM based on project analysis.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BootstrapPlan {
    /// Topic name for the project
    pub topic_name: String,
    /// Recommended pipeline name
    pub pipeline: String,
    /// Documents to import with skill mappings
    #[serde(default)]
    pub documents: Vec<BootstrapDoc>,
    /// Brief summary of analysis
    #[serde(default)]
    pub summary: String,
}

/// A document to import as part of bootstrap.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BootstrapDoc {
    /// Relative file path in the project
    pub path: String,
    /// Skill to map this document to
    pub skill: String,
    /// Document type (e.g. "prd", "rfc", "adr", "imported")
    pub doc_type: String,
    /// Document title
    #[serde(default)]
    pub title: String,
}

/// Result of executing a bootstrap plan.
#[derive(Debug, Clone, Serialize)]
pub struct BootstrapResult {
    pub topic_id: String,
    pub topic_name: String,
    pub pipeline_run_id: Option<String>,
    pub documents_imported: usize,
    pub summary: String,
}

/// Build the bootstrap prompt that an LLM uses to generate a BootstrapPlan.
///
/// The prompt includes:
/// 1. Project technical profile (from project-context.md)
/// 2. Project file tree
/// 3. Discovered documentation with content previews
/// 4. Module's bootstrap.md instructions
/// 5. Available skills and pipelines list
/// 6. Expected JSON response schema
pub fn build_bootstrap_prompt(
    project_context: &str,
    file_tree: &str,
    discovered_docs: &[DiscoveredDoc],
    bootstrap_md: Option<&str>,
    skills: &[String],
    pipelines: &[String],
) -> String {
    let mut prompt = String::new();

    prompt.push_str("You are analyzing a software project to set up a development workflow.\n\n");

    prompt.push_str("## Project Technical Profile\n\n");
    prompt.push_str(project_context);
    prompt.push_str("\n\n");

    prompt.push_str("## Project File Tree\n\n");
    prompt.push_str(file_tree);
    prompt.push_str("\n\n");

    prompt.push_str("## Discovered Documentation\n\n");
    if discovered_docs.is_empty() {
        prompt.push_str("No documentation files found.\n");
    } else {
        for doc in discovered_docs {
            prompt.push_str(&format!("### {} ({} bytes)\n\n", doc.path, doc.size));
            if !doc.preview.is_empty() {
                prompt.push_str("```\n");
                prompt.push_str(&doc.preview);
                prompt.push_str("\n```\n");
            }
            prompt.push('\n');
        }
    }
    prompt.push('\n');

    prompt.push_str("## Module Bootstrap Instructions\n\n");
    match bootstrap_md {
        Some(content) => prompt.push_str(content),
        None => prompt.push_str("No specific bootstrap instructions provided."),
    }
    prompt.push_str("\n\n");

    prompt.push_str("## Available Skills\n\n");
    if skills.is_empty() {
        prompt.push_str("(none)\n");
    } else {
        prompt.push_str(&skills.join(", "));
        prompt.push('\n');
    }
    prompt.push('\n');

    prompt.push_str("## Available Pipelines\n\n");
    if pipelines.is_empty() {
        prompt.push_str("(none)\n");
    } else {
        prompt.push_str(&pipelines.join(", "));
        prompt.push('\n');
    }
    prompt.push('\n');

    prompt.push_str("## Your Task\n\n");
    prompt.push_str(
        "Analyze this project and produce a bootstrap plan as JSON. Choose the most appropriate pipeline\n\
         and map existing documentation to the most relevant skills.\n\n\
         Respond with ONLY valid JSON in this format:\n\
         ```json\n\
         {\n  \
           \"topic_name\": \"project-name\",\n  \
           \"pipeline\": \"pipeline-name\",\n  \
           \"documents\": [\n    \
             {\"path\": \"relative/path.md\", \"skill\": \"skill-name\", \"doc_type\": \"type\", \"title\": \"Human Title\"}\n  \
           ],\n  \
           \"summary\": \"Brief description of what you found and why you chose this pipeline\"\n\
         }\n\
         ```\n",
    );

    prompt
}

/// Execute a bootstrap plan: create topic, import documents, optionally create pipeline run.
///
/// Returns a summary of actions taken.
pub fn execute_bootstrap_plan(
    plan: &BootstrapPlan,
    project_dir: &Path,
    start_pipeline: bool,
) -> crate::error::Result<BootstrapResult> {
    use crate::helpers::{find_pipeline, slugify};
    use crate::model::{Document, PipelineRun, Topic};
    use crate::storage::{FileStorage, IndexDb, ProjectLayout};

    let layout = ProjectLayout::new(project_dir);
    layout.ensure_initialized()?;
    let db = IndexDb::open(&layout.db_path())?;

    // Create topic
    let topic = Topic::new(&plan.topic_name, &plan.summary, "");
    db.create_topic(&topic)?;

    // Optionally create pipeline run
    let pipeline_run_id = if start_pipeline {
        let pipeline_def = find_pipeline(project_dir, &plan.pipeline)?;
        let run = PipelineRun::new(&pipeline_def, &plan.topic_name, &topic.id, "");
        db.upsert_pipeline_run(&run)?;
        Some(run.id)
    } else {
        None
    };

    // Import documents
    let mut imported = 0usize;
    for doc_spec in &plan.documents {
        let source_path = project_dir.join(&doc_spec.path);
        let content = match std::fs::read_to_string(&source_path) {
            Ok(c) => c,
            Err(_) => continue, // skip missing files
        };

        let title = if doc_spec.title.is_empty() {
            doc_spec.path.clone()
        } else {
            doc_spec.title.clone()
        };

        let mut document = Document::new(
            &doc_spec.doc_type,
            &title,
            &doc_spec.skill,
            pipeline_run_id.as_deref().unwrap_or(""),
            &topic.id,
        );
        document.status = "final".to_string();
        document.body = content;

        let slug = slugify(&title);
        let dest = layout
            .artifacts_dir()
            .join(format!("{}.{}.md", slug, doc_spec.doc_type));
        document.file_path = dest.clone();

        FileStorage::write_document(&document, &dest)?;
        db.upsert_document(&document)?;
        imported += 1;
    }

    Ok(BootstrapResult {
        topic_id: topic.id,
        topic_name: plan.topic_name.clone(),
        pipeline_run_id,
        documents_imported: imported,
        summary: plan.summary.clone(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_build_bootstrap_prompt_basic() {
        let prompt = build_bootstrap_prompt(
            "Rust project",
            "src/\n  main.rs",
            &[],
            None,
            &["prd".into(), "rfc".into()],
            &["standard".into()],
        );
        assert!(prompt.contains("## Project Technical Profile"));
        assert!(prompt.contains("Rust project"));
        assert!(prompt.contains("## Project File Tree"));
        assert!(prompt.contains("No documentation files found."));
        assert!(prompt.contains("No specific bootstrap instructions provided."));
        assert!(prompt.contains("prd, rfc"));
        assert!(prompt.contains("standard"));
        assert!(prompt.contains("## Your Task"));
        assert!(prompt.contains("topic_name"));
    }

    #[test]
    fn test_build_bootstrap_prompt_with_docs_and_bootstrap_md() {
        let docs = vec![DiscoveredDoc {
            path: "README.md".into(),
            size: 512,
            preview: "# My Project\nA cool project.".into(),
        }];
        let prompt = build_bootstrap_prompt(
            "Node project",
            "package.json\nsrc/",
            &docs,
            Some("Import README as the PRD."),
            &["product-prd".into()],
            &["light".into(), "standard".into()],
        );
        assert!(prompt.contains("README.md (512 bytes)"));
        assert!(prompt.contains("# My Project"));
        assert!(prompt.contains("Import README as the PRD."));
        assert!(prompt.contains("light, standard"));
    }

    #[test]
    fn test_bootstrap_plan_deserialize() {
        let json = r#"{
            "topic_name": "my-project",
            "pipeline": "standard",
            "documents": [
                {"path": "README.md", "skill": "product-prd", "doc_type": "prd", "title": "Product Requirements"}
            ],
            "summary": "Standard Rust project"
        }"#;
        let plan: BootstrapPlan = serde_json::from_str(json).unwrap();
        assert_eq!(plan.topic_name, "my-project");
        assert_eq!(plan.pipeline, "standard");
        assert_eq!(plan.documents.len(), 1);
        assert_eq!(plan.documents[0].skill, "product-prd");
    }

    #[test]
    fn test_bootstrap_plan_deserialize_minimal() {
        let json = r#"{"topic_name": "test", "pipeline": "light"}"#;
        let plan: BootstrapPlan = serde_json::from_str(json).unwrap();
        assert_eq!(plan.topic_name, "test");
        assert!(plan.documents.is_empty());
        assert!(plan.summary.is_empty());
    }
}
